"""Tests for oficina.prompt — monotonic-prefix prompt assembly (T2, P2-D2/D3).

Synchronous tests (plain ``def``). The ordering-guard test is the load-bearing one:
it is what keeps the P2-D2 cache invariant from silently rotting if SEGMENTS is edited.

Test names/docstrings pin the contract; bodies generated by the local model.

Not converted to the executable-spec DSL (`ref:test-executable-spec`): small structural suite
(ordering-guard invariants over SEGMENTS) — the DSL vocabulary would outweigh the tests.
"""

from ollama_mcp.oficina.prompt import SEGMENTS, Segment, build_prompt

# Stable parts only (iteration 1 — no repair feedback, no previous attempt).
STABLE_PARTS = {
    "system": "You are a Python coder.",
    "constraints": "One responsibility per function.",
    "context": "def caller(): return area(2, 3)",
    "tests": "assert area(2, 3) == 6",
    "objective": "Implement area(w, h).",
}

# The same stable parts plus iteration-2 variable parts.
FULL_PARTS = {
    **STABLE_PARTS,
    "repair_feedback": "NameError: area is not defined — define the function.",
    "previous_attempt": "def are(w, h): return w * h",
}


# --- ordering guard (the P2-D3 invariant) -----------------------------------


def test_all_stable_segments_precede_all_variable_segments():
    """Walking SEGMENTS in order, no stable segment may appear after any variable
    one — this is the P2-D2 monotonic-prefix invariant the guard protects."""
    seen_variable = False
    for segment in SEGMENTS:
        if not segment.stable:
            seen_variable = True
        else:
            assert not seen_variable, f"stable segment {segment.key!r} follows a variable one"


def test_segments_is_nonempty_and_has_both_kinds():
    """SEGMENTS has at least one stable and at least one variable segment, so the
    guard is actually exercising a real boundary (not vacuously true)."""
    assert any(s.stable for s in SEGMENTS)
    assert any(not s.stable for s in SEGMENTS)


# --- build_prompt fold ------------------------------------------------------


def test_build_prompt_orders_content_by_segments():
    """In the built prompt, each segment's content appears in SEGMENTS order
    (objective before repair_feedback before previous_attempt)."""
    prompt = build_prompt(FULL_PARTS)
    objective_index = prompt.find("Implement area")
    repair_index = prompt.find("NameError")
    previous_index = prompt.find("def are(")
    assert objective_index < repair_index < previous_index


def test_build_prompt_omits_blank_and_missing_parts():
    """A part that is missing or empty contributes nothing — iteration-1 output
    (STABLE_PARTS) contains neither the repair-feedback nor previous-attempt header."""
    prompt = build_prompt(STABLE_PARTS)
    assert "REPAIR FEEDBACK" not in prompt
    assert "PREVIOUS ATTEMPT" not in prompt


def test_build_prompt_includes_headers_for_present_parts():
    """A present part is rendered with its header label (e.g. 'OBJECTIVE:')."""
    prompt = build_prompt(STABLE_PARTS)
    assert "OBJECTIVE:" in prompt
    assert "CONSTRAINTS:" in prompt


def test_constraints_header_appears_once_with_loop_constants():
    """The loop's _CONSTRAINTS text must not embed its own 'CONSTRAINTS:' label — the segment
    header supplies it, so the assembled prompt shows the header exactly once (no doubling)."""
    from ollama_mcp.oficina.loop import _CONSTRAINTS, _SYSTEM

    prompt = build_prompt({"system": _SYSTEM, "constraints": _CONSTRAINTS, "objective": "do x"})
    assert prompt.count("CONSTRAINTS:") == 1


def test_iteration1_prompt_ends_with_objective():
    """With only stable parts, the last non-empty segment rendered is the objective
    (no variable segment trails it)."""
    prompt = build_prompt(STABLE_PARTS)
    assert prompt.rstrip().endswith("Implement area(w, h).")


# --- the cache contract (P2-D2): stable prefix is byte-identical ------------


def test_full_prompt_starts_with_stable_prefix():
    """build_prompt(FULL_PARTS) begins with exactly build_prompt(STABLE_PARTS) — the
    variable tail is strictly appended, so the reused KV prefix is byte-identical."""
    assert build_prompt(FULL_PARTS).startswith(build_prompt(STABLE_PARTS))


def test_changing_only_variable_parts_preserves_prefix():
    """Two full prompts that share STABLE_PARTS but differ in variable parts share
    the identical build_prompt(STABLE_PARTS) prefix."""
    other = {**STABLE_PARTS, "repair_feedback": "different", "previous_attempt": "def x(): pass"}
    stable_prefix = build_prompt(STABLE_PARTS)
    assert build_prompt(FULL_PARTS).startswith(stable_prefix)
    assert build_prompt(other).startswith(stable_prefix)


# --- current_file segment (T-110, E-D3): stable, between context and tests --


def test_current_file_segment_renders_between_context_and_tests():
    """The 'current_file' segment renders between context and tests, with its header
    and content appearing in the correct order."""
    parts = {
        **STABLE_PARTS,
        "current_file": "def area(w, h): return w * h",
    }
    prompt = build_prompt(parts)
    assert "CURRENT FILE" in prompt  # Header is present
    context_index = prompt.find("def caller(): return area(2, 3)")
    current_index = prompt.find("def area(w, h): return w * h")
    tests_index = prompt.find("assert area(2, 3) == 6")
    assert context_index < current_index < tests_index


def test_blank_current_file_is_omitted():
    """A blank 'current_file' part is omitted entirely — the header and content
    do not appear in the built prompt (greenfield stays byte-identical)."""
    parts = {**STABLE_PARTS, "current_file": ""}
    prompt = build_prompt(parts)
    assert "CURRENT FILE" not in prompt
