"""Tests for oficina.prompt — monotonic-prefix prompt assembly (T2, P2-D2/D3).

Synchronous tests (plain ``def``). The ordering-guard test is the load-bearing one:
it is what keeps the P2-D2 cache invariant from silently rotting if SEGMENTS is edited.

Test names/docstrings pin the contract; bodies generated by the local model.
"""

from ollama_mcp.oficina.prompt import SEGMENTS, Segment, build_prompt

# Stable parts only (iteration 1 — no repair feedback, no previous attempt).
STABLE_PARTS = {
    "system": "You are a Python coder.",
    "constraints": "One responsibility per function.",
    "context": "def caller(): return area(2, 3)",
    "tests": "assert area(2, 3) == 6",
    "objective": "Implement area(w, h).",
}

# The same stable parts plus iteration-2 variable parts.
FULL_PARTS = {
    **STABLE_PARTS,
    "repair_feedback": "NameError: area is not defined — define the function.",
    "previous_attempt": "def are(w, h): return w * h",
}


# --- ordering guard (the P2-D3 invariant) -----------------------------------


def test_all_stable_segments_precede_all_variable_segments():
    """Walking SEGMENTS in order, no stable segment may appear after any variable
    one — this is the P2-D2 monotonic-prefix invariant the guard protects."""
    seen_variable = False
    for segment in SEGMENTS:
        if not segment.stable:
            seen_variable = True
        else:
            assert not seen_variable, f"stable segment {segment.key!r} follows a variable one"


def test_segments_is_nonempty_and_has_both_kinds():
    """SEGMENTS has at least one stable and at least one variable segment, so the
    guard is actually exercising a real boundary (not vacuously true)."""
    assert any(s.stable for s in SEGMENTS)
    assert any(not s.stable for s in SEGMENTS)


# --- build_prompt fold ------------------------------------------------------


def test_build_prompt_orders_content_by_segments():
    """In the built prompt, each segment's content appears in SEGMENTS order
    (objective before repair_feedback before previous_attempt)."""
    prompt = build_prompt(FULL_PARTS)
    objective_index = prompt.find("Implement area")
    repair_index = prompt.find("NameError")
    previous_index = prompt.find("def are(")
    assert objective_index < repair_index < previous_index


def test_build_prompt_omits_blank_and_missing_parts():
    """A part that is missing or empty contributes nothing — iteration-1 output
    (STABLE_PARTS) contains neither the repair-feedback nor previous-attempt header."""
    prompt = build_prompt(STABLE_PARTS)
    assert "REPAIR FEEDBACK" not in prompt
    assert "PREVIOUS ATTEMPT" not in prompt


def test_build_prompt_includes_headers_for_present_parts():
    """A present part is rendered with its header label (e.g. 'OBJECTIVE:')."""
    prompt = build_prompt(STABLE_PARTS)
    assert "OBJECTIVE:" in prompt
    assert "CONSTRAINTS:" in prompt


def test_iteration1_prompt_ends_with_objective():
    """With only stable parts, the last non-empty segment rendered is the objective
    (no variable segment trails it)."""
    prompt = build_prompt(STABLE_PARTS)
    assert prompt.rstrip().endswith("Implement area(w, h).")


# --- the cache contract (P2-D2): stable prefix is byte-identical ------------


def test_full_prompt_starts_with_stable_prefix():
    """build_prompt(FULL_PARTS) begins with exactly build_prompt(STABLE_PARTS) — the
    variable tail is strictly appended, so the reused KV prefix is byte-identical."""
    assert build_prompt(FULL_PARTS).startswith(build_prompt(STABLE_PARTS))


def test_changing_only_variable_parts_preserves_prefix():
    """Two full prompts that share STABLE_PARTS but differ in variable parts share
    the identical build_prompt(STABLE_PARTS) prefix."""
    other = {**STABLE_PARTS, "repair_feedback": "different", "previous_attempt": "def x(): pass"}
    stable_prefix = build_prompt(STABLE_PARTS)
    assert build_prompt(FULL_PARTS).startswith(stable_prefix)
    assert build_prompt(other).startswith(stable_prefix)
