"""Tests for oficina.parser — the shared validator-output parser (T1).

Synchronous tests (plain ``def``), matching the P1 oficina test convention.

Division of authorship: the fixtures and test names/docstrings pin the
contract (P2-D7/D8/D12); the assertion bodies were generated by the local
model from those docstrings. Each test's docstring IS its spec.

Not converted to the executable-spec DSL (`ref:test-executable-spec`): the assertions fan across
heterogeneous kinds (stage / category / error_key / scope), so no small verb-family covers them
(rule 3), and the named fixtures already read as a spec. Low payoff.
"""

from ollama_mcp.oficina.parser import (
    CATEGORY_MECHANICAL,
    CATEGORY_STRUCTURAL,
    SCOPE_OUT,
    SCOPE_TARGET,
    SCOPE_TEST,
    STAGE_COMPILE,
    STAGE_TEST,
    ParsedFailure,
    category_for,
    parse_validator_output,
    scope_of,
)

# --- Fixtures: real output shapes -------------------------------------------

# validate-code.py emits a JSON *array* of per-file dicts (validate-code.py:690).
# A Python syntax error at line 12 in the target file:
COMPILE_FAIL = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 12)", "line": 12}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# The SAME syntax error but shifted to line 40 (e.g. more imports added above).
# error_key must be identical to COMPILE_FAIL's — line number is volatile.
COMPILE_FAIL_SHIFTED = [
    {
        "file": "area.py",
        "path": "/tmp/wt-xyz/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 40)", "line": 40}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# A clean compile: status pass, no errors.
COMPILE_PASS = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "pass",
        "errors": [],
        "warnings": [],
        "error_count": 0,
        "warning_count": 0,
        "load_time_ms": 2,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# Two files each with one error — parse must yield two failures.
COMPILE_TWO_FILES = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 12)", "line": 12}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    },
    {
        "file": "geom.py",
        "path": "/tmp/wt-abc/geom.py",
        "status": "fail",
        "errors": [
            {"type": "indentation_error", "text": "unexpected indent (geom.py, line 5)", "line": 5}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    },
]

# pytest short-summary text: a collection/import ERROR (mechanical — the
# undefined-name/import class py_compile cannot see, P2-D8 Python caveat).
PYTEST_ERROR = """\
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_area.py ______________________
ImportError while importing test module '/tmp/wt-abc/tests/test_area.py'.
E   ImportError: cannot import name 'area' from 'area'
=========================== short test summary info ============================
ERROR tests/test_area.py - ImportError: cannot import name 'area' from 'area'
============================== 1 error in 0.04s ================================
"""

# pytest short-summary text: an assertion FAILED (structural).
PYTEST_FAILED = """\
=================================== FAILURES ===================================
_________________________________ test_area ___________________________________
    def test_area():
>       assert area(2, 3) == 6
E       assert 5 == 6
tests/test_area.py:8: AssertionError
=========================== short test summary info ============================
FAILED tests/test_area.py::test_area - assert 5 == 6
============================== 1 failed in 0.03s ===============================
"""

# pytest all-green: no FAILED/ERROR lines.
PYTEST_PASS = """\
============================== 3 passed in 0.02s ===============================
"""


# --- stage → ParsedFailure: compile stage -----------------------------------


def test_compile_failure_has_compile_stage():
    """A failing compile payload yields a ParsedFailure whose stage is compile."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert failures
    assert all(failure.stage == STAGE_COMPILE for failure in failures)


def test_compile_failure_extracts_basename_as_file():
    """The failure's .file is the source basename ('area.py'), not the temp abs path."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all(failure.file == "area.py" for failure in failures)


def test_compile_failure_is_mechanical_category():
    """category_for a compile-stage failure is mechanical (P2-D8)."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


def test_compile_pass_yields_no_failures():
    """A payload where every file status is 'pass' parses to an empty list."""
    assert parse_validator_output(STAGE_COMPILE, COMPILE_PASS) == []


def test_two_failing_files_yield_two_failures():
    """One ParsedFailure per failing file across the JSON array."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_TWO_FILES)
    assert len(failures) == 2


def test_compile_failure_preserves_raw_text():
    """.raw retains the original error 'text' so the diff report can show it."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all("invalid syntax" in failure.raw for failure in failures)


# --- error_key normalization (P2-D7) ----------------------------------------


def test_error_key_stable_across_line_shift():
    """The SAME defect at line 12 vs line 40 produces an identical error_key —
    line numbers are volatile coordinates and must be stripped."""
    fail1 = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    fail2 = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL_SHIFTED)[0]
    assert fail1.error_key == fail2.error_key


def test_error_key_strips_absolute_paths():
    """No absolute path or temp-dir fragment (/tmp/wt-abc) survives in error_key."""
    fail = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    error_key = fail.error_key
    assert "/tmp" not in error_key[0] and "/tmp" not in error_key[1]
    assert "wt-abc" not in "".join(error_key)


def test_error_key_is_a_two_tuple_of_strings():
    """error_key is a (kind, detail) tuple of two strings for every failure."""
    fail = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    assert isinstance(fail.error_key, tuple)
    assert len(fail.error_key) == 2
    assert all(isinstance(part, str) for part in fail.error_key)


# --- stage → ParsedFailure: test stage (pytest) -----------------------------


def test_pytest_error_has_test_stage():
    """A pytest ERROR parses to a ParsedFailure whose stage is test."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_ERROR)
    assert failures
    assert all(failure.stage == STAGE_TEST for failure in failures)


def test_pytest_error_is_mechanical_category():
    """A pytest collection/import ERROR is mechanical (P2-D8 Python caveat):
    the undefined-name/import defect class py_compile cannot catch."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_ERROR)
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


def test_pytest_failed_is_structural_category():
    """A pytest assertion FAILED is structural (P2-D8)."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_FAILED)
    assert all(category_for(failure) == CATEGORY_STRUCTURAL for failure in failures)


def test_pytest_failure_extracts_worktree_relative_path():
    """.file is the nodeid's path prefix ('tests/test_area.py') — pytest already emits the
    worktree-relative spelling, so the parser must not destroy it to a basename (T-98)."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_FAILED)
    assert all(failure.file == "tests/test_area.py" for failure in failures)


def test_pytest_error_and_failed_key_differently():
    """ERROR and FAILED on the same nodeid produce different error_keys, so the
    category split survives into the repetition signature."""
    error = parse_validator_output(STAGE_TEST, PYTEST_ERROR)[0]
    failed = parse_validator_output(STAGE_TEST, PYTEST_FAILED)[0]
    assert error.error_key != failed.error_key


def test_pytest_pass_yields_no_failures():
    """Output with no FAILED/ERROR summary lines parses to an empty list."""
    assert parse_validator_output(STAGE_TEST, PYTEST_PASS) == []


# pytest output whose CODE UNDER TEST logs an ERROR line (log_cli / -s) but all tests pass:
# only the short-summary block is authoritative, so the log line must NOT become a failure.
PYTEST_PASS_WITH_APP_LOG = """\
ERROR    root:service.py:42 retry exhausted, giving up
FAILED   to connect on first try, retrying
============================== 2 passed in 0.05s ===============================
"""

# A test command that could not run at all: no short-summary block is emitted.
PYTEST_TOOLING_ERROR = "/bin/sh: 1: pytest: not found\n"


def test_pytest_application_log_lines_are_not_failures():
    """A green run whose application code logs 'ERROR ...'/'FAILED ...' lines outside the
    short-summary block parses to zero failures — only the summary block is authoritative."""
    assert parse_validator_output(STAGE_TEST, PYTEST_PASS_WITH_APP_LOG) == []


def test_pytest_output_without_summary_block_yields_no_failures():
    """Output with no 'short test summary info' block parses to [] — the caller distinguishes
    'passed' from 'never ran' via the exit code, not by an empty parse (see the evaluator)."""
    assert parse_validator_output(STAGE_TEST, PYTEST_TOOLING_ERROR) == []


# --- scope_of (P2-D12) ------------------------------------------------------


def test_scope_of_target_file():
    """A failure in a declared target file classifies as target."""
    result = scope_of("src/area.py", ["src/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_TARGET


def test_scope_of_test_file():
    """A failure in a declared test file classifies as test."""
    result = scope_of("tests/test_area.py", ["src/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_TEST


def test_scope_of_out_of_scope_file():
    """A failure in a file that is neither target nor test classifies as out —
    these are the only failures P2-D12 subtracts from the baseline."""
    result = scope_of("unknown.py", ["src/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_OUT


def test_scope_of_none_file_is_out():
    """An unattributable (None) file classifies as out."""
    result = scope_of(None, ["src/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_OUT


def test_scope_of_basename_collision_is_out():
    """T-98 regression: an out-of-scope file sharing the target's basename must be OUT —
    basename matching classified it target, so the wart was never subtracted and the loop
    could never pass (permanent false-exhaustion)."""
    result = scope_of("lib/util.py", ["src/util.py"], [])
    assert result == SCOPE_OUT


def test_scope_of_normalizes_path_spellings():
    """Dot-prefixed vs plain spellings of the same relative path still agree."""
    result = scope_of("./src/area.py", ["src/area.py"], [])
    assert result == SCOPE_TARGET


# --- language-derived error_key prefix (T-92 Phase 2) ------------------------

# validate-code.py emits the SAME JSON shape for Go (classify_go_error,
# validate-code.py:115) — but parser.py hardcoded "py-" on every compile error
# regardless of language, so a Go compile failure keyed as py-… and silently
# corrupted the P2-D7 repetition signature (the T-92 Phase 2 bug).
COMPILE_FAIL_GO = [
    {
        "file": "area.go",
        "path": "/tmp/wt-abc/area.go",
        "status": "fail",
        "errors": [
            {"type": "undefined_reference", "text": "undefined: mathutil.Volume", "line": 10}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 4,
        "validated_at": "2026-07-23T00:00:00.000Z",
    }
]


def test_compile_failure_under_go_keys_go_prefix():
    """A compile failure parsed with language="go" keys ("go-<type>", …), never "py-…" —
    the prefix is derived from the language the caller resolved (R1), not hardcoded."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL_GO, language="go")
    assert failures
    assert failures[0].error_key[0] == "go-undefined_reference"


def test_compile_failure_default_language_keys_py_prefix():
    """Omitting language preserves today's py- prefix byte-identically — every
    existing caller keeps its behavior with zero migration (the R1 default posture)."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert failures[0].error_key[0] == "py-syntax_error"


def test_compile_failure_under_full_language_name_keys_py_prefix():
    """language="python" (the R1 identifier resolve_language returns) keys "py-…" —
    the prefix spelling is mapped from the identifier, never echoed verbatim. Pins the
    seam the dispatch will cross: callers speak R1 vocabulary, keys keep their spelling."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL, language="python")
    assert failures[0].error_key[0] == "py-syntax_error"


def test_compile_error_key_detail_is_language_neutral():
    """Only the prefix half varies by language; the normalized detail half is computed
    from the message text alone, so the same text yields the same detail either way."""
    default = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    as_go = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL, language="go")[0]
    assert default.error_key[1] == as_go.error_key[1]


# --- _parse_gotest: go test -json event stream (T-92 Phase 3) ----------------

# Accessed via the module (not the top import) so that BEFORE the function exists,
# collection still succeeds and each test fails individually with a rich AttributeError —
# a top-level `from ... import _parse_gotest` would collapse the whole file into one
# thin `ERROR test_parser.py` collection error (the s126 repair-feedback gotcha).
from ollama_mcp.oficina import parser as parser_mod

# The module path of the worktree's go.mod — the parser strips it from the JSON
# events' Package field to recover the worktree-relative package directory.
GO_MODULE = "example.com/probe"

# Measured `go test -json ./...` event stream (session-124 experiment): one failing
# test in the module-root package. The authoritative failure signal is the
# Action:"fail" event WITH a non-empty Test — the trailing package-level fail event
# (no Test field) summarizes the package and must not double-count.
GOTEST_FAIL = """\
{"Action":"run","Package":"example.com/probe","Test":"TestArea"}
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"=== RUN   TestArea\\n"}
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"    area_test.go:11: Area(3,4) = 7, want 12\\n"}
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"--- FAIL: TestArea (0.00s)\\n"}
{"Action":"fail","Package":"example.com/probe","Test":"TestArea"}
{"Action":"output","Package":"example.com/probe","Output":"FAIL\\n"}
{"Action":"fail","Package":"example.com/probe"}
"""

# The SAME failure with the assertion moved to line 23 — line numbers are volatile
# coordinates (P2-D7); error_key must be identical to GOTEST_FAIL's.
GOTEST_FAIL_SHIFTED = """\
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"    area_test.go:23: Area(3,4) = 7, want 12\\n"}
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"--- FAIL: TestArea (0.00s)\\n"}
{"Action":"fail","Package":"example.com/probe","Test":"TestArea"}
{"Action":"fail","Package":"example.com/probe"}
"""

# A failure in a SUBPACKAGE: Package minus the module path names the package dir,
# so the file resolves worktree-relative (T-98: never bare basenames).
GOTEST_SUBPACKAGE_FAIL = """\
{"Action":"output","Package":"example.com/probe/geo","Test":"TestVolume","Output":"    volume_test.go:7: Volume(2,3,4) = 0, want 24\\n"}
{"Action":"output","Package":"example.com/probe/geo","Test":"TestVolume","Output":"--- FAIL: TestVolume (0.00s)\\n"}
{"Action":"fail","Package":"example.com/probe/geo","Test":"TestVolume"}
{"Action":"fail","Package":"example.com/probe/geo"}
"""

# Two distinct failing tests in one package — two failures, still no package-level
# double-count.
GOTEST_TWO_FAILURES = """\
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"    area_test.go:11: Area(3,4) = 7, want 12\\n"}
{"Action":"fail","Package":"example.com/probe","Test":"TestArea"}
{"Action":"output","Package":"example.com/probe","Test":"TestPerimeter","Output":"    area_test.go:19: Perimeter(3,4) = 12, want 14\\n"}
{"Action":"fail","Package":"example.com/probe","Test":"TestPerimeter"}
{"Action":"fail","Package":"example.com/probe"}
"""

# All green: pass events only.
GOTEST_PASS = """\
{"Action":"run","Package":"example.com/probe","Test":"TestArea"}
{"Action":"output","Package":"example.com/probe","Test":"TestArea","Output":"--- PASS: TestArea (0.00s)\\n"}
{"Action":"pass","Package":"example.com/probe","Test":"TestArea"}
{"Action":"output","Package":"example.com/probe","Output":"ok  \\texample.com/probe\\t0.002s\\n"}
{"Action":"pass","Package":"example.com/probe"}
"""

# A PASSING test whose own output prints '--- FAIL: ...' (e.g. a t.Log of captured
# text). The structural Action field is authoritative — text scraping would
# fabricate a failure here (the phantom-failure hole, closed for free by -json).
GOTEST_PASS_WITH_FAIL_TEXT = """\
{"Action":"output","Package":"example.com/probe","Test":"TestLogsFailText","Output":"    area_test.go:30: saw: --- FAIL: TestArea (0.00s)\\n"}
{"Action":"output","Package":"example.com/probe","Test":"TestLogsFailText","Output":"--- PASS: TestLogsFailText (0.00s)\\n"}
{"Action":"pass","Package":"example.com/probe","Test":"TestLogsFailText"}
{"Action":"pass","Package":"example.com/probe"}
"""


def test_gotest_fail_event_yields_one_test_stage_failure():
    """GOTEST_FAIL holds two Action:"fail" events (test + package summary) but exactly
    ONE is authoritative — the one with a non-empty Test. One ParsedFailure, stage test."""
    failures = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)
    assert len(failures) == 1
    assert failures[0].stage == STAGE_TEST


def test_gotest_failure_resolves_worktree_relative_file():
    """A module-root-package failure resolves .file to the _test.go path relative to
    the worktree root ('area_test.go') via the Package field + Output file:line."""
    failures = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)
    assert failures[0].file == "area_test.go"


def test_gotest_subpackage_failure_resolves_subdir_path():
    """A subpackage failure prefixes the package dir: Package 'example.com/probe/geo'
    under module 'example.com/probe' resolves .file to 'geo/volume_test.go' (T-98:
    worktree-relative, never a bare basename)."""
    failures = parser_mod._parse_gotest(GOTEST_SUBPACKAGE_FAIL, GO_MODULE)
    assert failures[0].file == "geo/volume_test.go"


def test_gotest_error_key_names_the_failing_test():
    """error_key kind is 'go-test-failed:' + the failing test's normalized identity, so
    the same test failing twice keys identically for the P2-D7 repetition signature."""
    failures = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)
    kind = failures[0].error_key[0]
    assert kind.startswith("go-test-failed:")
    assert "testarea" in kind.lower()


def test_gotest_error_key_stable_across_line_shift():
    """The same failure at output line 11 vs 23 yields an identical error_key — line
    numbers are volatile coordinates (P2-D7)."""
    fail1 = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)[0]
    fail2 = parser_mod._parse_gotest(GOTEST_FAIL_SHIFTED, GO_MODULE)[0]
    assert fail1.error_key == fail2.error_key


def test_gotest_two_failing_tests_yield_two_failures():
    """Two Action:"fail" events with distinct Test names yield two ParsedFailures;
    the package-level fail event still adds nothing."""
    failures = parser_mod._parse_gotest(GOTEST_TWO_FAILURES, GO_MODULE)
    assert len(failures) == 2
    assert failures[0].error_key != failures[1].error_key


def test_gotest_pass_yields_no_failures():
    """An all-green event stream parses to an empty list."""
    assert parser_mod._parse_gotest(GOTEST_PASS, GO_MODULE) == []


def test_gotest_fail_text_inside_passing_output_is_ignored():
    """A passing test whose OUTPUT text contains '--- FAIL: ...' yields no failures —
    the structural Action field is authoritative, never a text scrape of the output
    (the phantom-failure hole _summary_section exists for, closed for free by -json)."""
    assert parser_mod._parse_gotest(GOTEST_PASS_WITH_FAIL_TEXT, GO_MODULE) == []


def test_gotest_failure_preserves_raw_output():
    """.raw retains the failing test's output detail ('want 12') for the diff report."""
    failures = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)
    assert "want 12" in failures[0].raw


# --- _parse_go_build: go build stderr (T-92 Phase 3) -------------------------

# Measured `go build ./...` stderr (session-124 experiment): `# pkg` banner lines
# are non-failures; error lines are `./path:line:col: message` with a REAL
# worktree-relative path — compile attribution needs no stamp (R4).
GO_BUILD_FAIL = """\
# example.com/probe
./area.go:10:23: undefined: mathutil.Volume
./area.go:5:1: syntax error: unexpected }, expected expression
"""

# The SAME undefined-reference error at a different line:col — volatile
# coordinates must strip (P2-D7): error_key identical to GO_BUILD_FAIL's first.
GO_BUILD_FAIL_SHIFTED = """\
# example.com/probe
./area.go:40:7: undefined: mathutil.Volume
"""

# Subpackage errors + the remaining message classes. Paths keep their package
# dir (T-98: worktree-relative, never a bare basename).
GO_BUILD_CLASSES = """\
# example.com/probe/geo
./geo/volume.go:3:5: cannot use x (variable of type string) as int value
./geo/volume.go:7:2: "fmt" imported and not used
./geo/volume.go:9:1: weird unclassifiable failure
"""


def test_gobuild_banner_lines_are_skipped_and_errors_parsed():
    """The `# pkg` banner is not a failure; the two error lines each yield one
    ParsedFailure with stage compile."""
    failures = parser_mod._parse_go_build(GO_BUILD_FAIL)
    assert len(failures) == 2
    assert all(failure.stage == STAGE_COMPILE for failure in failures)


def test_gobuild_file_is_worktree_relative_without_dot_slash():
    """.file strips the leading './' but keeps the worktree-relative path."""
    failures = parser_mod._parse_go_build(GO_BUILD_FAIL)
    assert all(failure.file == "area.go" for failure in failures)


def test_gobuild_subpackage_file_keeps_package_dir():
    """A subpackage error's .file keeps its directory ('geo/volume.go') — T-98:
    basename-only attribution flips scope on collisions."""
    failures = parser_mod._parse_go_build(GO_BUILD_CLASSES)
    assert all(failure.file == "geo/volume.go" for failure in failures)


def test_gobuild_classifies_undefined_and_syntax():
    """Message-tail classification mirrors classify_go_error (validate-code.py:115):
    'undefined:' → go-undefined_reference; 'syntax error'/'expected' → go-syntax_error."""
    failures = parser_mod._parse_go_build(GO_BUILD_FAIL)
    assert failures[0].error_key[0] == "go-undefined_reference"
    assert failures[1].error_key[0] == "go-syntax_error"


def test_gobuild_classifies_type_unused_and_fallback():
    """'cannot use'/'type ' → go-type_error; 'imported and not used' →
    go-unused_import; anything unmatched falls back to go-compile_error."""
    kinds = [f.error_key[0] for f in parser_mod._parse_go_build(GO_BUILD_CLASSES)]
    assert kinds == ["go-type_error", "go-unused_import", "go-compile_error"]


def test_gobuild_error_key_stable_across_line_shift():
    """The same defect at 10:23 vs 40:7 keys identically — line:col are volatile
    coordinates (P2-D7)."""
    fail1 = parser_mod._parse_go_build(GO_BUILD_FAIL)[0]
    fail2 = parser_mod._parse_go_build(GO_BUILD_FAIL_SHIFTED)[0]
    assert fail1.error_key == fail2.error_key


def test_gobuild_preserves_raw_line():
    """.raw retains the original error line for the diff report."""
    failures = parser_mod._parse_go_build(GO_BUILD_FAIL)
    assert "undefined: mathutil.Volume" in failures[0].raw


def test_gobuild_empty_or_banner_only_stderr_yields_no_failures():
    """Empty stderr and banner-only stderr both parse to [] (a clean build)."""
    assert parser_mod._parse_go_build("") == []
    assert parser_mod._parse_go_build("# example.com/probe\n") == []


def test_gobuild_failures_are_mechanical_category():
    """Flat Go rule: every compile-stage failure is mechanical (asserted, not
    inherited by accident — same pinning stance as the go-test half)."""
    failures = parser_mod._parse_go_build(GO_BUILD_FAIL)
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


# --- flat Go category rule (T-92 Phase 3; folded into the _parse_gotest run) --


def test_go_compile_failure_is_mechanical_category():
    """Flat Go rule, compile half: every go- compile-stage failure is mechanical.
    (Already true structurally — category_for maps STAGE_COMPILE unconditionally —
    pinned here so the flat rule is asserted, not inherited by accident.)"""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL_GO, language="go")
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


def test_gotest_failure_is_structural_category():
    """Flat Go rule, test half: every go-test failure is structural — go build catches
    the undefined-name/import class at compile time, so Go needs no ERROR/FAILED split.
    The key must not fall through to category_for's ValueError crash path (which would
    kill the loop at classify time)."""
    failures = parser_mod._parse_gotest(GOTEST_FAIL, GO_MODULE)
    assert failures
    assert all(category_for(failure) == CATEGORY_STRUCTURAL for failure in failures)
