"""Tests for oficina.parser — the shared validator-output parser (T1).

Synchronous tests (plain ``def``), matching the P1 oficina test convention.

Division of authorship: the fixtures and test names/docstrings pin the
contract (P2-D7/D8/D12); the assertion bodies were generated by the local
model from those docstrings. Each test's docstring IS its spec.
"""

from ollama_mcp.oficina.parser import (
    CATEGORY_MECHANICAL,
    CATEGORY_STRUCTURAL,
    SCOPE_OUT,
    SCOPE_TARGET,
    SCOPE_TEST,
    STAGE_COMPILE,
    STAGE_TEST,
    ParsedFailure,
    category_for,
    parse_validator_output,
    scope_of,
)

# --- Fixtures: real output shapes -------------------------------------------

# validate-code.py emits a JSON *array* of per-file dicts (validate-code.py:690).
# A Python syntax error at line 12 in the target file:
COMPILE_FAIL = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 12)", "line": 12}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# The SAME syntax error but shifted to line 40 (e.g. more imports added above).
# error_key must be identical to COMPILE_FAIL's — line number is volatile.
COMPILE_FAIL_SHIFTED = [
    {
        "file": "area.py",
        "path": "/tmp/wt-xyz/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 40)", "line": 40}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# A clean compile: status pass, no errors.
COMPILE_PASS = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "pass",
        "errors": [],
        "warnings": [],
        "error_count": 0,
        "warning_count": 0,
        "load_time_ms": 2,
        "validated_at": "2026-07-15T00:00:00.000Z",
    }
]

# Two files each with one error — parse must yield two failures.
COMPILE_TWO_FILES = [
    {
        "file": "area.py",
        "path": "/tmp/wt-abc/area.py",
        "status": "fail",
        "errors": [
            {"type": "syntax_error", "text": "invalid syntax (area.py, line 12)", "line": 12}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    },
    {
        "file": "geom.py",
        "path": "/tmp/wt-abc/geom.py",
        "status": "fail",
        "errors": [
            {"type": "indentation_error", "text": "unexpected indent (geom.py, line 5)", "line": 5}
        ],
        "warnings": [],
        "error_count": 1,
        "warning_count": 0,
        "load_time_ms": 3,
        "validated_at": "2026-07-15T00:00:00.000Z",
    },
]

# pytest short-summary text: a collection/import ERROR (mechanical — the
# undefined-name/import class py_compile cannot see, P2-D8 Python caveat).
PYTEST_ERROR = """\
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_area.py ______________________
ImportError while importing test module '/tmp/wt-abc/tests/test_area.py'.
E   ImportError: cannot import name 'area' from 'area'
=========================== short test summary info ============================
ERROR tests/test_area.py - ImportError: cannot import name 'area' from 'area'
============================== 1 error in 0.04s ================================
"""

# pytest short-summary text: an assertion FAILED (structural).
PYTEST_FAILED = """\
=================================== FAILURES ===================================
_________________________________ test_area ___________________________________
    def test_area():
>       assert area(2, 3) == 6
E       assert 5 == 6
tests/test_area.py:8: AssertionError
=========================== short test summary info ============================
FAILED tests/test_area.py::test_area - assert 5 == 6
============================== 1 failed in 0.03s ===============================
"""

# pytest all-green: no FAILED/ERROR lines.
PYTEST_PASS = """\
============================== 3 passed in 0.02s ===============================
"""


# --- stage → ParsedFailure: compile stage -----------------------------------


def test_compile_failure_has_compile_stage():
    """A failing compile payload yields a ParsedFailure whose stage is compile."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert failures
    assert all(failure.stage == STAGE_COMPILE for failure in failures)


def test_compile_failure_extracts_basename_as_file():
    """The failure's .file is the source basename ('area.py'), not the temp abs path."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all(failure.file == "area.py" for failure in failures)


def test_compile_failure_is_mechanical_category():
    """category_for a compile-stage failure is mechanical (P2-D8)."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


def test_compile_pass_yields_no_failures():
    """A payload where every file status is 'pass' parses to an empty list."""
    assert parse_validator_output(STAGE_COMPILE, COMPILE_PASS) == []


def test_two_failing_files_yield_two_failures():
    """One ParsedFailure per failing file across the JSON array."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_TWO_FILES)
    assert len(failures) == 2


def test_compile_failure_preserves_raw_text():
    """.raw retains the original error 'text' so the diff report can show it."""
    failures = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)
    assert all("invalid syntax" in failure.raw for failure in failures)


# --- error_key normalization (P2-D7) ----------------------------------------


def test_error_key_stable_across_line_shift():
    """The SAME defect at line 12 vs line 40 produces an identical error_key —
    line numbers are volatile coordinates and must be stripped."""
    fail1 = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    fail2 = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL_SHIFTED)[0]
    assert fail1.error_key == fail2.error_key


def test_error_key_strips_absolute_paths():
    """No absolute path or temp-dir fragment (/tmp/wt-abc) survives in error_key."""
    fail = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    error_key = fail.error_key
    assert "/tmp" not in error_key[0] and "/tmp" not in error_key[1]
    assert "wt-abc" not in "".join(error_key)


def test_error_key_is_a_two_tuple_of_strings():
    """error_key is a (kind, detail) tuple of two strings for every failure."""
    fail = parse_validator_output(STAGE_COMPILE, COMPILE_FAIL)[0]
    assert isinstance(fail.error_key, tuple)
    assert len(fail.error_key) == 2
    assert all(isinstance(part, str) for part in fail.error_key)


# --- stage → ParsedFailure: test stage (pytest) -----------------------------


def test_pytest_error_has_test_stage():
    """A pytest ERROR parses to a ParsedFailure whose stage is test."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_ERROR)
    assert failures
    assert all(failure.stage == STAGE_TEST for failure in failures)


def test_pytest_error_is_mechanical_category():
    """A pytest collection/import ERROR is mechanical (P2-D8 Python caveat):
    the undefined-name/import defect class py_compile cannot catch."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_ERROR)
    assert all(category_for(failure) == CATEGORY_MECHANICAL for failure in failures)


def test_pytest_failed_is_structural_category():
    """A pytest assertion FAILED is structural (P2-D8)."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_FAILED)
    assert all(category_for(failure) == CATEGORY_STRUCTURAL for failure in failures)


def test_pytest_failure_extracts_test_file_basename():
    """.file is the test module basename ('test_area.py') from the nodeid."""
    failures = parse_validator_output(STAGE_TEST, PYTEST_FAILED)
    assert all(failure.file == "test_area.py" for failure in failures)


def test_pytest_error_and_failed_key_differently():
    """ERROR and FAILED on the same nodeid produce different error_keys, so the
    category split survives into the repetition signature."""
    error = parse_validator_output(STAGE_TEST, PYTEST_ERROR)[0]
    failed = parse_validator_output(STAGE_TEST, PYTEST_FAILED)[0]
    assert error.error_key != failed.error_key


def test_pytest_pass_yields_no_failures():
    """Output with no FAILED/ERROR summary lines parses to an empty list."""
    assert parse_validator_output(STAGE_TEST, PYTEST_PASS) == []


# --- scope_of (P2-D12) ------------------------------------------------------


def test_scope_of_target_file():
    """A failure in a declared target file classifies as target."""
    result = scope_of("area.py", ["/tmp/wt-abc/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_TARGET


def test_scope_of_test_file():
    """A failure in a declared test file classifies as test."""
    result = scope_of("test_area.py", ["/tmp/wt-abc/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_TEST


def test_scope_of_out_of_scope_file():
    """A failure in a file that is neither target nor test classifies as out —
    these are the only failures P2-D12 subtracts from the baseline."""
    result = scope_of("unknown.py", ["/tmp/wt-abc/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_OUT


def test_scope_of_none_file_is_out():
    """An unattributable (None) file classifies as out."""
    result = scope_of(None, ["/tmp/wt-abc/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_OUT


def test_scope_of_matches_by_basename():
    """Absolute-path target declaration still matches a basename-only failure file."""
    result = scope_of("area.py", ["/tmp/wt-abc/area.py"], ["tests/test_area.py"])
    assert result == SCOPE_TARGET
